#!/usr/bin/env bash
# Install Docker + Docker Compose plugin, run presence_ws, install Caddy, write site config.
# Run as root on Debian/Ubuntu. Usage:
#   ./bootstrap-host.sh presence.example.com
# Optional second arg: email for ACME (Let's Encrypt), e.g. admin@example.com
#
# Repo layout: .../frappe_pulse/presence_ws/deploy/bootstrap-host.sh

set -euo pipefail

DOMAIN="${1:-}"
ACME_EMAIL="${2:-}"

if [[ -z "$DOMAIN" || "$DOMAIN" == -* ]]; then
	echo "Usage: $0 <public-domain> [acme-email@optional]" >&2
	echo "Example: $0 presence.example.com admin@example.com" >&2
	exit 1
fi

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRESENCE_WS="$(cd "${DEPLOY_DIR}/.." && pwd)"
cd "$PRESENCE_WS"

if [[ "$(id -u)" -ne 0 ]]; then
	echo "Run as root (sudo)." >&2
	exit 1
fi

echo "==> presence_ws directory: $PRESENCE_WS"

install_docker() {
	if command -v docker >/dev/null 2>&1; then
		echo "==> Docker already installed"
		return 0
	fi
	echo "==> Installing Docker (docker.io + compose plugin)…"
	apt-get update -qq
	DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker.io docker-compose-plugin
	systemctl enable --now docker
	echo "==> Docker ready"
}

compose_up() {
	if [[ ! -f docker-compose.yml ]]; then
		echo "docker-compose.yml not found in $PRESENCE_WS" >&2
		exit 1
	fi
	# Bind presence only on localhost when Caddy terminates TLS on this host
	if [[ ! -f docker-compose.override.yml ]]; then
		if [[ -f deploy/docker-compose.override.caddy.yml ]]; then
			cp -a deploy/docker-compose.override.caddy.yml docker-compose.override.yml
			echo "==> Created docker-compose.override.yml (127.0.0.1:${PRESENCE_WS_PORT:-8765})"
		fi
	fi
	[[ -f .env ]] || cp deploy/env.example .env
	if [[ -f .env ]]; then
		set -a
		# shellcheck disable=SC1091
		source .env
		set +a
	fi
	echo "==> docker compose build + up -d"
	docker compose build presence-ws
	docker compose up -d
	# quick check (no X-Api-Token — ok if PRESENCE_X_API_TOKEN unset)
	sleep 2
	if curl -fsS "http://127.0.0.1:${PRESENCE_WS_PORT:-8765}/health" >/dev/null; then
		echo "==> GET /health OK on 127.0.0.1:${PRESENCE_WS_PORT:-8765}"
	else
		echo "WARN: /health did not return 200 (check .env PRESENCE_X_API_TOKEN or logs: docker compose logs presence-ws)" >&2
	fi
}

install_caddy() {
	if command -v caddy >/dev/null 2>&1; then
		echo "==> Caddy already installed"
	else
		echo "==> Installing Caddy (official stable repo)…"
		apt-get update -qq
		apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl gnupg
		curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
		curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' >/etc/apt/sources.list.d/caddy-stable.list
		apt-get update -qq
		DEBIAN_FRONTEND=noninteractive apt-get install -y -qq caddy
	fi
}

write_caddyfile() {
	local cf="/etc/caddy/Caddyfile"
	local tmp
	tmp="$(mktemp)"
	{
		echo "# Generated by frappe_pulse presence_ws/deploy/bootstrap-host.sh"
		if [[ -n "$ACME_EMAIL" ]]; then
			echo "{"
			echo "	email ${ACME_EMAIL}"
			echo "}"
		fi
		echo "${DOMAIN} {"
		echo "	encode zstd gzip"
		echo "	reverse_proxy 127.0.0.1:${PRESENCE_WS_PORT:-8765}"
		echo "}"
	} >"$tmp"
	if [[ -f "$cf" ]] && ! cmp -s "$tmp" "$cf"; then
		cp -a "$cf" "${cf}.bak.$(date +%Y%m%d%H%M%S)"
		echo "==> Backed up previous $cf"
	fi
	mv "$tmp" "$cf"
	chmod 0644 "$cf"
	echo "==> Wrote $cf for https://$DOMAIN → 127.0.0.1:${PRESENCE_WS_PORT:-8765}"
}

reload_caddy() {
	systemctl enable caddy >/dev/null 2>&1 || true
	if caddy validate --config /etc/caddy/Caddyfile; then
		systemctl reload caddy || systemctl restart caddy
		echo "==> Caddy reloaded. Try: wss://$DOMAIN/ (with ?user_id=… or ?ticket=…)"
	else
		echo "WARN: caddy validate failed; check /etc/caddy/Caddyfile" >&2
		systemctl status caddy --no-pager -l || true
	fi
}

install_docker
compose_up
install_caddy
write_caddyfile
reload_caddy

echo
echo "Done. DNS A/AAAA for $DOMAIN must point to this server for automatic HTTPS."
echo "If GET /health requires PRESENCE_X_API_TOKEN, set it in $PRESENCE_WS/.env and redeploy: docker compose up -d"
